### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by majid-rehman** [IvanKuchin/SAST#1]
I am getting this error on workflow run. My repository is private and I am using default sast.yaml privided by you. 
{
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/commits/comments#create-a-commit-comment",
  "status": "403"
}

**Comment by IvanKuchin** [comment]
Script is not able to commit comment. 
To solve the problem add permission to your yaml:
```yaml
 permissions:
   issues: write 
```

More info is here: https://docs.github.com/en/actions/use-cases-and-examples/project-management/commenting-on-an-issue-when-a-label-is-added

**Comment by IvanKuchin** [comment]
Hope the issue has been resolved. 
Please reopen it , unless above is true
